# Generated by Django 5.0.6 on 2024-06-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ENGLISH", "english"), ("HINDI", "hindi")],
                        default="HINDI",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
