# Generated by Django 5.0.6 on 2024-06-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_translate"),
    ]

    operations = [
        migrations.AddField(
            model_name="translate",
            name="translated_content",
            field=models.TextField(default="HINDI"),
        ),
    ]
