# Generated by Django 5.0.6 on 2024-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_translate_translated_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voice_Translate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ENGLISH", "english"),
                            ("HINDI", "hindi"),
                            ("TAMIL", "tamil"),
                        ],
                        default="HINDI",
                        max_length=10,
                    ),
                ),
                ("translated_content", models.TextField(default="HINDI")),
                ("cotent", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="translate",
            name="language",
            field=models.CharField(
                choices=[
                    ("ENGLISH", "english"),
                    ("HINDI", "hindi"),
                    ("TAMIL", "tamil"),
                ],
                default="HINDI",
                max_length=10,
            ),
        ),
    ]
