# Generated by Django 5.0.6 on 2024-07-04 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_voice_translate_alter_translate_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voice_translate",
            old_name="cotent",
            new_name="content",
        ),
    ]
